---
development:
  cloud_name: eli
  api_key: <%= ENV['CLOUDINARY_ID'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: eli
  api_key: <%= ENV['CLOUDINARY_ID'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: eli
  api_key: <%= ENV['CLOUDINARY_ID'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
